### ISSUE TITLE
Makefile needs to update PATH for go-gx

### ISSUE THREAD

**Issue by philipbeadle** [metacurrency/holochain#294] opened 2017-07-25 06:18 UTC
When the dependencies for go-gx and gx are retrieved the executables wont run unless the PATH variable is updated with $GOBIN value.

**Comment by zippy** [comment] 2017-07-26 01:47
Hi Philip, so there are some explicitly instructions on this in the README, and it's definitely where most people have problems, i.e. not doing that step as listed under the Unix section of the go-based install, but if you do that it works without setting $GOBIN, just $GOPATH

Is there some way we could improve the instructions so that it would have worked better?  Or perhaps I'm not fully understanding the issue. Maybe you installed your go bin somepace other than our instructions assumed?

**Comment by philipbeadle** [comment] 2017-07-26 23:01
Hi Eric, Thtat's exactly where I went wrong.  Problem is the instructions for the Go install are before the PATH update step so the ```make``` won't work. Might be better to do the platform steps before the Go installation step.  I'll change the README and make a pull request for you.

**Comment by philipbeadle** [comment] 2017-07-26 23:44
the makefile made the hc executable but the instructions are using the newer ```hcadmin -v```

Philips-MacBook-Pro-2:holochain philipbeadle$ hcadmin -v
-bash: hcadmin: command not found
Philips-MacBook-Pro-2:holochain philipbeadle$ hc -v
hc version 0.0.6 (holochain 12)

**Comment by philipbeadle** [comment] 2017-07-26 23:55
So I commented out each block at a time and got all the commands installed.  

# hc: deps
# 	go get $(REPO)/cmd/hc
# 	gx-go rewrite --undo
# hcd: deps
# 	go get $(REPO)/cmd/hcd
# 	gx-go rewrite --undo
# hcdev: deps
# 	go get $(REPO)/cmd/hcdev
# 	gx-go rewrite --undo
# hcadmin: deps
# 	go get $(REPO)/cmd/hcadmin
# 	gx-go rewrite --undo
# bs: deps
# 	go get $(REPO)/cmd/bs
# 	gx-go rewrite --undo
test: deps
	$(foreach pkg_path,$(go_packages),go get -d -t $(pkg_path) && go test $(TEST_FLAGS) $(pkg_path)${new_line})
	gx-go rewrite --undo
test-sample: hc

And now it works
Philips-MacBook-Pro-2:holochain philipbeadle$ hcadmin -v
hcadmin version 0.0.1 (holochain 12)

**Comment by philipbeadle** [comment] 2017-07-27 01:06
Got the same issue using Docker.  The only built file is ```hc```

**Comment by zippy** [comment] 2017-07-27 01:59
Yah, thanks I made the mistake of moving the newer hcdev family ahead to quickly without making changes in all the other spaces and docs.  My bad.  Glad you could get it straightened out.

**Comment by zippy** [comment] 2017-07-28 02:42
fixed by: e166ac137

**Closed** 2017-07-28 02:41 UTC

**Comment by zippy** [comment] 2017-07-28 02:44
the build problem was actually caused by the Makefile default recipie only building hc.  e166ac137 adds a default all recipie that builds all the commands.
